name: Publish escad.dev

on:
  push:
    branches: [deno-deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: extractions/setup-just@v1

      - run: just build-escad-dev

      - uses: denoland/deployctl@v1
        with:
          project: tjjfvi-escad-deno-deploy
          entrypoint: https://deno.land/std/http/file_server.ts
          root: escad.dev
