name: Publish escad.dev

on:
  push:
    branches: [prod]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: extractions/setup-just@v1

      - run: just build-escad-dev

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: tjjfvi/escad.dev
          publish_dir: ./escad.dev
          cname: escad.dev
