name: Publish Playground

on:
  push:
    branches: [deno]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: PROD=1 deno run -A --unstable --no-check src/playground/devServer.ts

      - run: mkdir playground
      - run: mv src/playground/static/* playground/
      - run: mv playground/file:/$PWD/src/playground/{mod.js,sw.js} playground/
      - run: mv playground/mod.js playground/main.js
      - run: mv src/* playground/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground
          cname: escad.dev
