name: Publish Playground

on:
  push:
    branches: [deno]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: escad.run
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'tjjfvi',
              repo: 'escad.run',
              workflow_id: 'publish.yml',
              ref: 'main'
            })
